server:
  port: 8091
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/TalentPool?useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: TalentPoolUser
    password: talentpooluser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs.html
  packagesToScan: com.pragma.crecimiento.monolito.micro.personas.infraestructure.endpoint
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost